### ISSUE TITLE
two readarr instances are not possible

### ISSUE THREAD

**Issue by ReggY85** [PCJones/UmlautAdaptarr#42]
this configuration causes errors in the container
      
      - READARR__0__NAME=readarrBooks
      - READARR__0__ENABLED=true
      - READARR__0__HOST=xxx
      - READARR__0__APIKEY=xxx
      - READARR__1__NAME=readarrAudioBooks
      - READARR__1__ENABLED=true
      - READARR__1__HOST=xxx
      - READARR__1__APIKEY=xxx

**Comment by PCJones** [comment]
What error exactly?

**Comment by ReggY85** [comment]
`   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)

   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)

   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)

   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)

   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)

   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)

   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)

   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)

   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)

   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)

   at Program.Main(String[] args) in /app/UmlautAdaptarr/Program.cs:line 90`

**Comment by PCJones** [comment]
Can you share the rest of your environment variables please?

**Comment by ReggY85** [comment]
LIDARR__APIKEY=xxx
RADARR__HOST=http://xxx
LIDARR__ENABLED=true
SONARR__APIKEY=xxx
LIDARR__HOST=http://xxx
SONARR__HOST=http://xxx
READARR__0__APIKEY=xxx
READARR__0__ENABLED=true
READARR__0__HOST=http://xxx.1
READARR__1__APIKEY=xxx
READARR__1__ENABLED=true
READARR__1__HOST=http://xxx.2
SONARR__ENABLED=true
RADARR__ENABLED=true
TZ=Europe/Berlin
RADARR__APIKEY=xxx
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
APP_UID=1654
ASPNETCORE_HTTP_PORTS=8080
DOTNET_RUNNING_IN_CONTAINER=true
DOTNET_VERSION=8.0.6
ASPNET_VERSION=8.0.6

**Comment by S2ciOnur** [comment]
READARR? 
Is that correct? Can this be handled in the Container?
I'm asking for a friend.

**Comment by PCJones** [comment]
> READARR? Is that correct? Can this be handled in the Container? I'm asking for a friend.

What exactly are you asking about? You can answer in German if you want

**Comment by S2ciOnur** [comment]
Alles gut, ich bin einfach spät Abends am Freitag nimmt mein IQ exponentiell ab. Dachte der Kollege wollte Radarr nutzen und hat stattdessen readarr in die environments gepackt.
Mein Fehler. Ignoriert mich einfach.
Ich war nie hier.

**Comment by PCJones** [comment]
@ReggY85 can you please check 

> LIDARR__APIKEY=xxx RADARR__HOST=http://xxx LIDARR__ENABLED=true SONARR__APIKEY=xxx LIDARR__HOST=http://xxx SONARR__HOST=http://xxx READARR__0__APIKEY=xxx READARR__0__ENABLED=true READARR__0__HOST=http://xxx.1 READARR__1__APIKEY=xxx READARR__1__ENABLED=true READARR__1__HOST=http://xxx.2 SONARR__ENABLED=true RADARR__ENABLED=true TZ=Europe/Berlin RADARR__APIKEY=xxx PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin APP_UID=1654 ASPNETCORE_HTTP_PORTS=8080 DOTNET_RUNNING_IN_CONTAINER=true DOTNET_VERSION=8.0.6 ASPNET_VERSION=8.0.6

This is working fine for me. Are you using unraid? Can you please download the newest update and then share the log from the beginning?

**Comment by ReggY85** [comment]
Vielen Dank für deine Antwort. Es scheint jetzt bei mir zu funktionieren. Woran es genau lag, weiß ich nicht, aber ich habe das Image neu heruntergeladen, und jetzt sieht alles gut aus. Ich verwende Portainer auf einem Linux XLC unter Proxmox.
Ein Großteil der Arrs hat aber auch gerade ein Update bekommen.

**Comment by PCJones** [comment]
Dann lag das sicherlich an einem Bug in 0.6 der mit 0.6.1 gefixt wurde :)

**Comment by ReggY85** [comment]
Ich muss mich leider noch einmal zu dem Thema melden. 

Bei der Konfiguration von zwei Readarr-Instanzen oder auch bei einer mit Nummerierung werden die Suchergebnisse ohne Umlaute angezeigt. Wenn jedoch nur eine Instanz ohne Nummerierung konfiguriert ist, erscheinen die Ergebnisse in beiden Readarr-Instanzen korrekt. Es scheint also noch ein Problem vorzuliegen.

iO:
- READARR__APIKEY=xxx
- READARR__ENABLED=true
- READARR__HOST=http://xxx.1

niO:
- READARR__0__APIKEY=xxx
- READARR__0__ENABLED=true
- READARR__0__HOST=http://xxx.1
- READARR__1__APIKEY=xxx
- READARR__1__ENABLED=true
- READARR__1__HOST=http://xxx.2

auch niO:
- READARR__0__APIKEY=xxx
- READARR__0__ENABLED=true
- READARR__0__HOST=http://xxx.1

**Comment by PCJones** [comment]
Ich bin hier weiter dran, sorry. Ich melde mich sobald es etwas neues gibt

**Comment by m4tz3** [comment]
Yes, unfortunately, I have encountered the same problem. I can't get two Readarr instances to run. (Why two: one for eBooks and one for audiobooks).
