### ISSUE TITLE
Indexer funktionieren nicht mit umlautadaptarr in prowlarr

### ISSUE THREAD

**Issue by Baine** [PCJones/UmlautAdaptarr#49]
Grüße,

die meisten meiner Indexer funktionieren leider nicht, wenn UmlautAdaptarr dazwischen geschaltet ist

meldung in prowlarr (webui)
```
Unable to connect to indexer, please check your DNS settings and ensure IPv6 is working or disabled. Received an invalid status code: 'Not'.
```
meldung in prowlarr stdout
```
[Warn] Cardigann: Unable to connect to indexer

[v1.25.4.4818] System.Net.Http.HttpRequestException: Received an invalid status code: 'Not'.
   at System.Net.Http.HttpConnection.ParseStatusLine(ReadOnlySpan`1 line, HttpResponseMessage response)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Prowlarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 120
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Prowlarr.Common/Http/HttpClient.cs:line 171
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 43
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.<>c.<<FetchIndexerResponse>b__57_0>d.MoveNext() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 661
--- End of stack trace from previous location ---
   at Polly.ResiliencePipeline.<>c__9`2.<<ExecuteAsync>b__9_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Outcome`1.GetResultOrRethrow()
   at Polly.ResiliencePipeline.ExecuteAsync[TResult,TState](Func`3 callback, TState state, CancellationToken cancellationToken)
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 660
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 583
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 760


[Warn] ProwlarrErrorPipeline: Invalid request Validation failed:
 -- : Unable to connect to indexer, please check your DNS settings and ensure IPv6 is working or disabled. Received an invalid status code: 'Not'.
```

kein Eintrag im stdout von UmlautAdaptarr zu der Anfrage (aber auch keine Beschwerde das auf HTTP umgestellt werden müsste)
Tag für den Indexer
![{EB243A2F-200A-4FFD-8169-9ADD035B34E1}](https://github.com/user-attachments/assets/852ca3a4-fe43-43e7-b3bb-517e23673754)

Proxy Einstellungen in Prowlarr
![{837AF3E7-C7F6-418C-8CA2-24EF1AC7881C}](https://github.com/user-attachments/assets/a84a0875-4910-48b1-af28-a3e38a3914e0)

umlautadaptarr ist über den namen zu finden für prowlarr:
```
docker exec -it prowlarr sh
root@359beea7ba2e:/# ping umlautadaptarr
PING umlautadaptarr (172.22.0.32): 56 data bytes
64 bytes from 172.22.0.32: seq=0 ttl=64 time=0.078 ms
64 bytes from 172.22.0.32: seq=1 ttl=64 time=0.075 ms
^C
--- umlautadaptarr ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.075/0.076/0.078 ms
```

Hab ich etwas übersehen, oder wie lässt sich das lösen?

Habe scenenzbs wie in der doku einzeln hinzugefügt da nicht in Prowlarr direkt vorhanden mittels http://umlautadaptarr:5005/_/scenenzbs.com und das läuft ohne Probleme.
Ebenson funktionieren tntracker und NZBGeek in Prowlarr;
AnimeWorld (API), HeadPhones VIP, RuTracker.org, Torrenting, TorrentLeech, TorrentSyndikat funktionieren leider nicht :(

(P.S.: gibt es eine einfachere Methode zur Umstellung von HTTPS zu HTTP als über die DB direkt, wenn Prowlarr keine direkte Bearbeitung erlaubt?)

**Comment by PCJones** [comment]
> (P.S.: gibt es eine einfachere Methode zur Umstellung von HTTPS zu HTTP als über die DB direkt, wenn Prowlarr keine direkte Bearbeitung erlaubt?)

Nein, leider nicht. Ich überlege aber, ob ich das durch den UmlautAdaptarr automatisieren kann.

Die ganzen genannten Tracker funktionieren nicht, weil sie keine Newznab bzw. Torznab API anbieten (bei Headphones und AnimeWorld bin ich mir nicht sicher). Für TS kommt eine extra Lösung, für den Rest wahrscheinlich nicht.

Alle Usenet-Indexer nutzen eine Newznab-API, TNTracker nutzt Torznab, deshalb funktioniert das auch.

**Comment by Baine** [comment]
Animeworld hat eine eigene API, also nicht Torznab
Gibt wohl diverse Implementierungen der Indexer:
| Name | Implementation |
| ------------- | ------------- |
| TorrentLeech | Cardigann |
|AnimeWorld (API) | Cardigann |
|RuTracker.org | RuTracker |
|Torrent Network | Torznab |
|TorrentSyndikat | TorrentSyndikat |
|Torrenting | Cardigann |
|Headphones VIP | Headphones |
|NZBgeek | Newznab |

schade dass es nur mit Torznab und Newznab klappt (wahrscheinlich wegen der verwendeten felder in der response?)

Dann weiß ich aber, das ich nicht weiter zu probieren brauche^^

Danke für deine Zeit, UmlautAdaptarr und die Antwort!

Mach dann mal zu :)

**Comment by PCJones** [comment]
TS kommt wie gesagt noch, für Animes würde ich den UmlautAdaptarr sowieso nicht empfehlen. Und öffentliche Tracker haben sowieso fast nichts an deutschen Inhalten, da lohnt sich der Aufwand auch nicht.

Bei Headphones dachte ich immer, das wäre auch ein Usenet Indexer? Die haben kein Newznab?

Und ein kleiner Tipp noch, wir haben eine wirklich sehr nette und hilfsbereite Discord-Community zum Thema Usenet, Torrents, Automatisierung, Jellyfin/Plex und co - wenn ich mir deine Indexer & Tracker so angucke würdest du da gut reinpassen :D 

https://discord.gg/pZrrMcJMQM

**Comment by Baine** [comment]
während headphones n usenet indexer ist, scheinen die nicht als newznab in prowlarr eingerichtet worden zu sein
(zumind. als eigene klasse, siehe https://github.com/Prowlarr/Prowlarr/blob/25afadc9b2e5e20539bddebea904aab72a36f5d1/src/NzbDrone.Core/Indexers/Definitions/Headphones/Headphones.cs#L14
)
Probiere die Tage mal ob ich es als generic newznab mit der URL einrichten kann, ggF direkt in lidarr analog zu scenenzbs
schaue bei gelegenheit im discord vorbei, vllt kann ich mir das eine oder andere noch abgucken/verbessern oder vllt sogar beisteuern :)
